services:
  postgres:
    image: postgres:16
    container_name: mesa-agil-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mesa-agil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: