spring.datasource.url=jdbc:postgresql://localhost:5432/mesa-agil
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create